contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #fludevpipeline channel"
    url: https://nfcore.slack.com/channels/fludevpipeline
    about: Discussion about the nf-core/fludevpipeline pipeline
